### ISSUE TITLE
Potentially update the images

### ISSUE THREAD

**Issue by bynect** [dunst-project/docker-images#10]
Right now I get a deprecation messages from every action
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, codecov/codecov-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

So we may want to update the images. However I am not an expert in docker (I wrote the last Dockerfile 4/5 years ago) so I am not sure what to do (without breaking anything).

**Comment by fwsmit** [comment]
The docker files got updated recently. But they need to get rebuilt and pushed to docker hub. I don't know exactly how. I think @bebehei has the credentials for docker hub.

**Comment by bebehei** [comment]
TBH, I have to have a look there.

I guess, I should move this to the GitHub registry, so anyone inside the dunst org can update this without needing to get another permission on another platform.


The docs look just right for this:

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by bebehei** [comment]
So, I'm currently testing to build the docker images on GitHub Actions itself.

After spinning up the matrix (I've taken it from our main project), I've hit the same error message, but in Debian Stretch: https://github.com/dunst-project/docker-images/actions/runs/8132245691/job/22222455338

Stretch is totally outdated and we should ignore it. Hence we should drop it from the CI in our main repo.

**Comment by bebehei** [comment]
Ok, kind of false alarm with Debian Stretc. The debian strech dockerfile is not available anymore, hence this job failed.

After fixing the matrix list, the build works, but now [**every** matrix job warns with this message](https://github.com/dunst-project/docker-images/actions/runs/8132293623).

![image](https://github.com/dunst-project/docker-images/assets/2073458/57f9cba6-f54c-4a89-9d1c-833faf9e6b4a)


Dafuq? I've just created this pipeline and took the reference code from GitHub docs? Can't they just keep the code up to date?

---

To derive the actions in main repo:

- Update the distro list in matrix in main workflow
- Update the serials from the actions

**Comment by bebehei** [comment]
It's getting wild here. I know, I'm the newbie here, but ... what?

![image](https://github.com/dunst-project/docker-images/assets/2073458/d35d94da-dbbf-4115-86a3-3dd8f91b5403)

---

> I've just created this pipeline and took the reference code from GitHub docs? Can't they just keep the code up to date?

I've checked out the docs from the docker actions itselves. All reference v3 in their docs. But apparently those docs are outdated, too. 🙈

**Comment by bebehei** [comment]
So, it seems like the images can be built now on GitHub Actions, also by yourselves. Additionally, when updating the files here, there is no need to do manual rebuilds.

**Comment by bebehei** [comment]
Ahh, it seems like the package is still not visible. I cannot pull it:

```text
[benediktheine:~/code/dunst/docker-images] master(+8/-14) ± docker pull ghcr.io/dunst-project/docker-images:alpine
Error response from daemon: Head "https://ghcr.io/v2/dunst-project/docker-images/manifests/alpine": unauthorized
[benediktheine:~/code/dunst/docker-images] master(+8/-14) 1 ±
```

Found a hint in the [package's settings](https://github.com/orgs/dunst-project/packages/container/docker-images/settings): 

![image](https://github.com/dunst-project/docker-images/assets/2073458/745991c0-dd01-4ac6-bb77-3dd51494d552)

But I'm not allowed to change it:

![image](https://github.com/dunst-project/docker-images/assets/2073458/c8898943-83a8-45e3-bbd6-0b91e20b794e)

EDIT:

It's in the [Org's settings](https://github.com/organizations/dunst-project/settings/packages)

![image](https://github.com/dunst-project/docker-images/assets/2073458/b80c9727-c8ad-46a6-80ec-6d1673de71fe)

**Comment by bebehei** [comment]
Just found in this repository the old Docker Hub Hooks, removed them.

**Comment by bebehei** [comment]
Oh, this wasn't the brightest action by myself today: I already killed the docker hub dunst organisation. (the old CI cannot run anymore from now, sorry)

**Comment by bynect** [comment]
good work, I have no clue how to manage docker 😢

**Comment by zappolowski** [comment]
@bynect we have new images already running on the CI since a while. Can we close this one?

**Comment by bynect** [comment]
Sure
