### ISSUE TITLE
Werror is not enabled on pushed images?

### ISSUE THREAD

**Issue by fwsmit** [dunst-project/docker-images#4]
In the Makefile `CFLAGS` is set to `-Werror`, probably for the best. On the images that are used in the dunst repo, it seems like that is not set, however. As you can see on the ubuntu-xenial run here: https://github.com/dunst-project/dunst/pull/803/checks?check_run_id=2101783749, or the archlinux run here: https://github.com/dunst-project/dunst/pull/803/checks?check_run_id=2101783807. Warnings are generated, but no error. When running locally -Werror is set.

**Comment by bebehei** [comment]
Well, this is correct. Setting `-Werror` in the CI would help and prevent bugs.

But I guess, this should be done in the GitHub Actions Workflow. It should something work like `make CFLAGS="-Werror" -j all`.
